ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN set -x \
  && apt-get update \
  && apt-get install --no-install-recommends -y \
      sqlite3 \
      nano vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
